export const SEQUELIZE = 'SEQUELIZE';

//Module Constants
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ACCOUNT_REPOSITORY = 'ACCOUNT_REPOSITORY';
export const USERS_ACCOUNT_REPOSITORY = 'USERS_ACCOUNT_REPOSITORY';
